config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "users#show"
  resources :users, only: [:index, :show, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :groups, only: [:new, :create, :edit, :update, :destroy] do
    resources :events, only: [:index, :create, :show, :edit, :update, :destroy] do
      resources :messages, only: :create
      
      namespace :api do
        resources :messages, only: :index, defaults: { format: 'json'}
      end

    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group, optional: true
  belongs_to :user
  has_many :messages,foreign_key: :event_id, dependent: :destroy

  validates :title, presence: true,length: { maximum: 20 } 
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users,foreign_key: :group_id, dependent: :destroy
  has_many :events,foreign_key: :group_id, dependent: :destroy
  has_many :messages,foreign_key: :group_id, dependent: :destroy


  validates :name, presence: true,length: { maximum: 20 } 
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :event
  belongs_to :group
  belongs_to :user

  validates :content,presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, uniqueness: true,length: {maximum: 20}

  has_many :group_users
  has_many :groups, through: :group_users,foreign_key: :user_id, dependent: :destroy
  has_many :events,foreign_key: :user_id, dependent: :destroy
  has_many :messages

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  mount_uploader :image, ImageUploader
  mount_uploader :imageicon, BackgroundImageUploader

  def self.search(input,id)
    return nil if input == ""
    User.where(['name LIKE?', "%#{input}%"]).where.not(id: id).limit(10)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    event = Event.find(params[:event_id])
    @messages = event.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end
  def after_sign_out_path_for(resource)
    new_user_session_path # ログアウト後に遷移するpathを設定
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_group
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @event = Event.new
    @events = @group.events.includes(:user).order(start_date: "DESC")
    @friend = current_user.followings & current_user.followers if !current_user.nil? 
    
  end
  def show
    @message = Message.new
    @messages = @event.messages.includes(:user)
  end
  
  def create
    @event = @group.events.new(event_params)
    if @event.save
      redirect_to group_events_path(@group), notice: 'メッセージが送信されました'
    else
      @events = @group.events.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
      
      respond_to do |format|
        format.html
        format.json
      end
    end
  end

  def edit
  end
  
  def update
    @event.update(event_params)
    redirect_to group_event_path(@group,@event)
  end

  def destroy
    @event.destroy
    redirect_to group_events_path(@group)

  end
  
  private

  def event_params
    params.require(:event).permit(:title, :content, :start_date, :end_date, :group_id).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update, :destroy]

  def new
    @group = Group.new
    @group.users << current_user
    @friend = current_user.followings & current_user.followers if !current_user.nil? 
  end
  
  def create
    @group = Group.create(group_params)
    @group.save
    redirect_to group_events_path(@group), notice: 'カレンダーを作成しました'
  end
  
  def edit
    @friend = current_user.followings & current_user.followers if !current_user.nil? 
  end
  
  def update
    @group.update(group_params)
    redirect_to group_events_path(@group), notice: 'カレンダーを編集しました'
  end

  def destroy
    if @group.destroy
      redirect_to user_path(current_user), notice: 'カレンダーを削除しました'
    end
  end



  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group
  before_action :set_event
  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end
  
  def create
    @message = Message.create(message_params)
    respond_to do |format|
      # format.html{ redirect_to group_event_path(@group,@event),notice: "メッセージを送信しました"}
      format.json
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id, event_id: params[:event_id], group_id: params[:group_id])
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:notice] = 'ユーザーをフォローしました'
      redirect_to :back
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to :back
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:notice] = 'ユーザーのフォローを解除しました'
      redirect_to :back
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to :back
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.search(params[:keyword], current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def show
    # @group = Group.find(params[:id])
    @events = @user.events.order(start_date: "DESC")
    @users = User.where.not(id: current_user.id)
    @friend = @user.followings & @user.followers if !current_user.nil? 
    @follow = @user.followings if !current_user.nil?
    @follower = @user.followers if !current_user.nil?
    @userEvent = @user.groups.order(created_at: "DESC").flat_map(&:events).group_by{|event| event.group}
    
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :content, :image, :imageicon, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_calendar_top.html.haml
.calendar-top
  %i.fas.fa-bars.fa-lg.btn__tab2
  #calendar
    .new-content
      = render "form"
    .member-list
      %p Member List
      - @group.users.each do |user|
        .member-list__show
          .member-list__image
          -if user.imageicon?
            =link_to user_path(user),class: "member-list__name-link" do
              = image_tag user.imageicon,class:"member-list__image-icon"
            .member-list__name
            =link_to user_path(user),class: "member-list__name-link" do
              = user.name
          -else 
            =link_to user_path(user),class: "member-list__name-link" do
              = image_tag "/images/default.jpg",class:"member-list__image-icon"
            .member-list__name
            =link_to user_path(user),class: "member-list__name-link" do
              = user.name

      
.time-content
  .day-time
    %i.day-time__icon.far.fa-calendar-plus.fa-2x
    = @group.name + "の予定"
    - @events.each do |event|
      .day-time__contents{data: {event: {id: event.id}}}
        .day-time__start
          = event.start_date.to_s(:datetime_jp)+"~" 
        .day-time__name
          = link_to user_path(event.user.id),class: "day-time__username" do
            = image_tag event.user.imageicon,class: "day-time__imageicon"
            = event.user.name
        .day-time__title
          .day-time__shows
            = link_to group_event_path(@group,event),class: "day-time__show" do
              %i.fas.fa-link
              =event.title
          -if user_signed_in? && current_user.id == event.user.id
            .day-time__deletes
            = link_to group_event_path(@group,event),class: "show-content__delete", method: :delete, data: { confirm: '予定を削除してもよろしいでしょうか？' } do
              %i.far.fa-trash-alt.show-content__d-icon 
          
            

app/views/events/_edit.html.haml
.field__path
  %i.fas.fa-times.back-icon
%h2 予定を編集してください
= form_for [@group, @event] do |f|
  = f.label :予定, class: "new-content__label"
  = f.text_field :title, class: "new-content__text"
  = f.label :内容, class: "new-content__label"
  = f.text_field :content, class: "new-content__text"
  %p 開始時間
  = f.datetime_local_field :start_date
  %p 終了時間
  = f.datetime_local_field :end_date
  .new-content__btn
    = f.submit "update",class: "new-content__btnitem"

app/views/events/_form.html.haml
%i.back-icon.fas.fa-times
%h2 新しい予定を入力してください
= form_for [@group, @event] do |f|
  = f.label :予定, class: "new-content__label"
  = f.text_field :title, class: "new-content__text"
  = f.label :内容, class: "new-content__label"
  = f.text_field :content, class: "new-content__text"
  %p 開始時間
  = f.datetime_local_field :start_date
  %p 終了時間
  = f.datetime_local_field :end_date
  .new-content__btn
    = f.submit "new create",class: "new-content__btnitem"

app/views/events/_side_bar.html.haml
.side-bar
  .side-top
    .menu
      .group-menu
        %ul MENU
      .group-home
        = link_to user_path(current_user.id) do
          %li マイページ
      #group-create.group-home
        = link_to new_group_path do
          %li カレンダーを作成する
      #group-edit.group-home
        = link_to edit_group_path(@group) do
          %li カレンダーを編集する
      #group-delete.group-home
        = link_to group_path(@group),method: :delete,data: { confirm: 'カレンダーを削除してもよろしいでしょうか？' } do
          %li カレンダーを削除する
      .group-list
        %li Calendar List
        .group-list__open
          - current_user.groups.each do |group|
            .group-list__name
              = link_to group_events_path(group) do
                = group.name
.navber
  %i.member-icon.fas.fa-users.fa-2x
  %i.side-icon.far.fa-folder-open.fa-2x

app/views/events/index.html.haml
.wrapper
  = render "side_bar"
  = render "calendar_top"

app/views/events/show.html.haml
.show-main
  .main-top{data: {event: {id: @event.id}}}
    = link_to group_events_path(@group),class: "show-content__back" do
      %i.fas.fa-home CalendarHome
    .show-content
      .show-content__title
        予定
        %br/
        = @event.title
      
      -if user_signed_in? && current_user.id == @event.user.id
        .show-content__menu
          .show-content__edit
            %i.far.fa-edit.fa-lg.show-content__e-icon 
          = link_to group_event_path(@group,@event),class: "show-content__delete", method: :delete, data: { confirm: '予定を削除してもよろしいでしょうか？' } do
            %i.far.fa-trash-alt.fa-lg.show-content__d-icon 
    .show-content__start
      開始:
      = @event.start_date.to_s(:datetime_jp)
    .show-content__start
      終了:
      = @event.end_date.to_s(:datetime_jp)
    .show-content__description
      詳細
      %br/
      = @event.content
    #new-content.new-content
      = render "edit"
    
  .messages
    .message
      - @messages.each do |message|
        .message-list{data: {message: {id: message.id}}}
          .message-list__top
            .message-list__user-name
              = message.user.name
            .message-list__created_at
              = message.created_at.to_s(:datetime_jp)

          .message-list__content
            = message.content
          .message-list__image
            = image_tag message.image.url,class: "message-list__img" if message.image.present?
          
    .message-form
      = form_for [@group, @event, @message] do |f|
        .form-input
          = f.text_field :content,  class: "form-input__text-field", placeholder: 'メッセージを入力してください'
          .message-form__menu
            = f.label :image,class: "form-input__label" do
              = f.file_field :image, class: "form-input__tag"
        = f.submit "Send",class: "form-input__btn"

app/views/groups/_edit.html.haml
.group-form-edit
  %i.back-icon.fas.fa-times.fa-lg
  %h1 カレンダーの編集

  = form_for @group do |f|
    .group-main
      #group-users
        %h3 Friend List
        - @friend.each do |user|
          .group-user.jss-add-user
            = image_tag user.imageicon,class: "group-user__image"
            %p.group-user__name 
              = user.name
            .group-user__btn--add{"data-user-id" => user.id, "data-user-name" => user.name} 追加
      
      .group-form__field
        .group-form__text
          = f.label :name, class: 'group-form__label'
          = f.text_field :name, class: 'group-form__input', placeholder: 'グループ名を入力してください'

        .group-form__member
          .group-form__member--list
            %label.group-form__label 
            メンバー
          #group-user__list.js-add-user
            .group-user__list
              %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
              %p.group-user__name 
                = current_user.name

            - @group.users.each do |user|
              - if current_user.name != user.name
                #group-user__list
                  .group-user__list
                    %input{name: "group[user_ids][]", type: "hidden", value: user.id}
                    %p.group-user__name
                      = user.name 
                    %a.group-user__btn--remove
                      削除
        .group-form__submit
          = f.submit class: 'group-form__action-btn'


  

app/views/groups/_form.html.haml
= form_for @group do |f|
  .group-main
    #group-users
      %h3 Friend List
      - @friend.each do |user|
        .group-user{"data-user-id" => user.id, "data-user-name" => user.name, "data-user-imageicon" => user.imageicon}
          -if user.imageicon?
            = image_tag user.imageicon,class: "group-user__image"
            %p.group-user__name 
              = user.name
          -else
            = image_tag "/images/default.jpg",class: "group-user__image", alt: "ユーザーアイコン"
            %p.group-user__name 
              = user.name
          
          .group-user__btn--add{"data-user-id" => user.id, "data-user-name" => user.name, "data-user-imageicon" => user.imageicon} 追加
    
    .group-form__field
      .group-form__text
        = f.label :name, class: 'group-form__label'
        = f.text_field :name, class: 'group-form__input', placeholder: 'グループ名を入力してください'

      .group-form__member
        .group-form__member--list
          %label.group-form__label 
          メンバー
        #group-user__list.js-add-user
          .group-user__list
            %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
            %p.group-user__name 
              = current_user.name

      .group-form__submit
        = f.submit class: 'group-form__action-btn'

app/views/groups/edit.html.haml
.group-form-edit
  = link_to :back do
    %i.back-icon.fas.fa-times.fa-lg
  %h1 カレンダーの編集

  = form_for @group do |f|
    .group-main
      #group-users
        %h3 Friend List
        - @friend.each do |user|
          .group-user{"data-user-id" => user.id, "data-user-name" => user.name, "data-user-imageicon" => user.imageicon}
            -if user.imageicon?
              = image_tag user.imageicon,class: "group-user__image"
              %p.group-user__name 
                = user.name
            -else
              = image_tag "/images/default.jpg",class: "group-user__image", alt: "ユーザーアイコン"
              %p.group-user__name 
                = user.name
              
            .group-user__btn--add{"data-user-id" => user.id, "data-user-name" => user.name, "data-user-imageicon" => user.imageicon} 追加
      
      .group-form__field
        .group-form__text
          = f.label :name, class: 'group-form__label'
          = f.text_field :name, class: 'group-form__input', placeholder: 'グループ名を入力してください'

        .group-form__member
          .group-form__member--list
            %label.group-form__label 
            メンバー
          #group-user__list.js-add-user
            .group-user__list
              %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
              %p.group-user__name 
                = current_user.name

            - @group.users.each do |user|
              - if current_user.name != user.name
                #group-user__list
                  .group-user__list
                    %input{name: "group[user_ids][]", type: "hidden", value: user.id}
                    %p.group-user__name
                      = user.name 
                    %a.group-user__btn--remove{"data-user-id" => user.id, "data-user-name" => user.name, "data-user-imageicon" => user.imageicon}
                      削除
        .group-form__submit
          = f.submit class: 'group-form__action-btn'


  

app/views/groups/new.html.haml
.group-form
  = link_to :back do
    %i.back-icon.fas.fa-times.fa-lg
  %h1 新規カレンダー作成
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width,initial-scale=1.0", :name => "viewport"}/

    %title TaskCalendar
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    %link{ rel: "stylesheet", type: "text/css", href: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"}
    = javascript_include_tag 'application', media: 'all'
    %script{ type: "text/javascript", src: "//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"}
  %body{"data-turbolinks" => "false"}
    -if user_signed_in?
      .header
        .header-left
          %i.fas.fa-fan.fa-2x
          = link_to user_path(current_user),class: "header-left__link" do
            %h2 Task Calendar
          %ul.header-left__main
            = link_to user_path(current_user),class: "header-left__link" do
              %li.header-left__calendar
                カレンダー
            = link_to "#",class: "header-left__link" do
              %li.header-left__blog
                ブログ
            = link_to "#",class: "header-left__link" do
              %li.header-left__blog
                ヘルプ
        .header-right
          %ul.header-right__menu
            %li.header-right__info
              %i.header-right__icon1.far.fa-file-alt.fa-2x
                .header-right__info-icon1
                  ご意見・ご要望
            %li.header-right__info
              %i.header-right__icon2.far.fa-bell.fa-2x
                .header-right__info-icon2
                  お知らせ
            %li.header-right__info
              = link_to destroy_user_session_path, method: :delete, class: "header-right__delete" do
                %i.header-right__icon3.fas.fa-user-circle.fa-2x
                .header-right__info-icon3
                  ログアウト

    = render 'layouts/notifications'
    = yield

app/views/relationships/_follow.html.haml
- unless current_user == @user
  - if current_user.following?(@user)
    = form_for(current_user.relationships.find_by(follow_id: @user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: @user.id
      = f.submit 'フォロー中', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: @user.id
      = f.submit 'フォロー', class: 'follows'

app/views/relationships/_follower.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー中', class: 'follow-now'

  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'フォロー', class: 'follows'
      

app/views/users/_edit.html.haml
.account-page.account-page__edit
  .account-page__inner
    .account-page__header
      %i.back-icon.fas.fa-times.fa-lg
      %h2 Edit Account
      %h5 アカウントの編集
      -# = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      -# = link_to "トップページに戻る", :back, class: 'btn'
    .user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
          .field-label
            = f.label :introduction
          .field-input
            = f.text_field :content, autofocus: true
          .field-label
            = f.label :image
          .field-input
            = f.file_field :imageicon
          .field-label
            = f.label :背景
          .field-input
            = f.file_field :image
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/show.html.haml
.wrapper
  #group.group
    .group-top
      .group-user
        .group-menu
          %ul MENU
        .group-home
          = link_to user_path(current_user) do
            %li ホーム
        .group-home.group-userlist
          %li ユーザーリスト
        .group-home.group-followlist
          %li フォロー/フォロワー
        .group-home
          = link_to new_group_path do
            %li カレンダーを作成する
      -if user_signed_in? && current_user.id == @user.id
        .group-list
          %li Calendar List
          .group-list__open
            - @user.groups.each do |group|
              .group-list__name
                = link_to group_events_path(group) do
                  = group.name
  .user-main
    .user-content
      %i.fas.fa-bars.fa-lg.btn__tab
      %i.fas.fa-bars.fa-lg.btn__tab3
      .user-content__image
        -if @user.image?
          = image_tag @user.image,class: "user-content__back-image"
        -else
          = image_tag "/images/pl1234.jpg",class: "user-content__back-image", alt: "背景写真"
        -if @user.imageicon?
          .user-content__icon
            = image_tag @user.imageicon,class: "user-content__default-image"
        -else
          .user-content__icon-default
            = image_tag "/images/default.jpg",class: "user-content__default-image", alt: "ユーザーアイコン"
      .user-content__menu
        .user-content__name
          = @user.name
        .user-content__edits
        -if user_signed_in? && current_user.id == @user.id
          .user-content__edit
            Edit profile
        -else
          .user-content__edit-back
            = render "relationships/follow"
      .user-content__friend
        = "Friend  #{@friend.count}人"
      .user-content__greet
        -if @user.content?
          = simple_format @user.content
        -else
          Hello World!! 
      
    = render "edit"

    .event-tag
      .event-tag__user
        = @user.name + "さんの予定" 
      .event-tag__friend
        Friend List
    
    .user-show 
      Friend List
      - @friend.each do |user|
        .user-show__list
          .user-show__member
            =link_to user_path(user),class: "user-show__name" do
              -if user.imageicon?
                = image_tag user.imageicon, class: "user-show__imageicon"
                = user.name
              -else
                = image_tag "/images/default.jpg",class: "user-show__imageicon"
                = user.name
          .user-show__created_at
            = user.created_at.strftime("%Y年%m月")+"からTask Calendarを利用しています"

    .event-main
      -if user_signed_in? && current_user.id == @user.id
        - @userEvent.each do |key,event|
          .event-list
            = link_to group_events_path(key.id),class: "event-list__link" do
              %i.fas.fa-users
              = key.name
          -event.sort!.reverse!.first(3).each do |event|
            .event-list__top
              .event-list__title
                = link_to group_event_path(event.group_id,event),class: "event-list__title--color" do
                  %i.event-list__title--icon.fas.fa-external-link-alt
                  = event.title
              .event-list__start
                = event.start_date.to_s(:datetime_jp)+"~"
            
      -else
        .event-main__userless
          %p 本ユーザーの予定は公開されていません
    
  .all-user
    .user-search
      %h3 User Search
      %input#user-search__input{placeholder: "検索したいユーザー名を入力してください"}
        #user-search__result
    
    .all-user__content
      .all-user__show
        .all-user__tag--follower 
          %p フォロワー 
        .all-user__tag--follow
          %p フォロー
      
      .all-user__follower-list
        - @follower.each do |user|
          .all-user__list
            .all-user__list-member
              =link_to user_path(user) do
                -if user.imageicon?
                  = image_tag user.imageicon,class: "all-user__image"
                -else
                  = image_tag "/images/default.jpg",class: "all-user__image"
              =link_to user_path(user),class: "all-user__name" do
                = user.name
            .all-user__follow
              = render partial: 'relationships/follower',locals: {user: user}
            
      .all-user__follow-list
        - @follow.each do |user|
          .all-user__list
            .all-user__list-member
              =link_to user_path(user) do
                -if user.imageicon?
                  = image_tag user.imageicon,class: "all-user__image"
                -else
                  = image_tag "/images/default.jpg",class: "all-user__image"
              =link_to user_path(user),class: "all-user__name" do
                = user.name
            .all-user__follow
              = render partial: 'relationships/follower',locals: {user: user}

    .all-user__main
      %h3 User List
      - @users.each do |user|
        .all-user__list
          .all-user__list-member
            =link_to user_path(user) do
              -if user.imageicon?
                = image_tag user.imageicon,class: "all-user__image"
              -else
                = image_tag "/images/default.jpg",class: "all-user__image"
            =link_to user_path(user),class: "all-user__name" do
              = user.name
          .all-user__follow
            = render partial: 'relationships/follower',locals: {user: user}